package com.example.commonlibrary.bean.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.commonlibrary.bean.CommonData;
import com.example.commonlibrary.widget.manager.music.base.MusicPlayBean;
import com.example.commonlibrary.widget.manager.video.base.VideoPlayBean;
import com.example.commonlibrary.net.download.FileInfo;

import com.example.commonlibrary.bean.greendao.CommonDataDao;
import com.example.commonlibrary.bean.greendao.MusicPlayBeanDao;
import com.example.commonlibrary.bean.greendao.VideoPlayBeanDao;
import com.example.commonlibrary.bean.greendao.FileInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig commonDataDaoConfig;
    private final DaoConfig musicPlayBeanDaoConfig;
    private final DaoConfig videoPlayBeanDaoConfig;
    private final DaoConfig fileInfoDaoConfig;

    private final CommonDataDao commonDataDao;
    private final MusicPlayBeanDao musicPlayBeanDao;
    private final VideoPlayBeanDao videoPlayBeanDao;
    private final FileInfoDao fileInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        commonDataDaoConfig = daoConfigMap.get(CommonDataDao.class).clone();
        commonDataDaoConfig.initIdentityScope(type);

        musicPlayBeanDaoConfig = daoConfigMap.get(MusicPlayBeanDao.class).clone();
        musicPlayBeanDaoConfig.initIdentityScope(type);

        videoPlayBeanDaoConfig = daoConfigMap.get(VideoPlayBeanDao.class).clone();
        videoPlayBeanDaoConfig.initIdentityScope(type);

        fileInfoDaoConfig = daoConfigMap.get(FileInfoDao.class).clone();
        fileInfoDaoConfig.initIdentityScope(type);

        commonDataDao = new CommonDataDao(commonDataDaoConfig, this);
        musicPlayBeanDao = new MusicPlayBeanDao(musicPlayBeanDaoConfig, this);
        videoPlayBeanDao = new VideoPlayBeanDao(videoPlayBeanDaoConfig, this);
        fileInfoDao = new FileInfoDao(fileInfoDaoConfig, this);

        registerDao(CommonData.class, commonDataDao);
        registerDao(MusicPlayBean.class, musicPlayBeanDao);
        registerDao(VideoPlayBean.class, videoPlayBeanDao);
        registerDao(FileInfo.class, fileInfoDao);
    }
    
    public void clear() {
        commonDataDaoConfig.clearIdentityScope();
        musicPlayBeanDaoConfig.clearIdentityScope();
        videoPlayBeanDaoConfig.clearIdentityScope();
        fileInfoDaoConfig.clearIdentityScope();
    }

    public CommonDataDao getCommonDataDao() {
        return commonDataDao;
    }

    public MusicPlayBeanDao getMusicPlayBeanDao() {
        return musicPlayBeanDao;
    }

    public VideoPlayBeanDao getVideoPlayBeanDao() {
        return videoPlayBeanDao;
    }

    public FileInfoDao getFileInfoDao() {
        return fileInfoDao;
    }

}
